import React from "react";
import Link from "next/link";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { ArrowLeft, FileText, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Terms of Service | TraceSearch",
  description: "Terms and conditions governing the use of TraceSearch.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background text-text-primary">
      <Navbar />

      <main className="flex-1 w-full max-w-[840px] mx-auto px-4 sm:px-8 py-8 sm:py-12">
        <div className="mb-6">
          <Link href="/">
            <Button variant="ghost" size="sm" className="gap-1.5 text-xs text-text-secondary">
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Back to Research</span>
            </Button>
          </Link>
        </div>

        <article className="space-y-8 animate-fade-in text-left">
          <header className="border-b border-border pb-6 space-y-2">
            <div className="inline-flex items-center gap-2 text-xs font-semibold text-ocean-deep uppercase tracking-wider">
              <FileText className="w-4 h-4" />
              <span>Agreement</span>
            </div>
            <h1 className="font-h1 text-text-primary tracking-tight">
              Terms of Service
            </h1>
            <p className="text-xs text-text-muted">
              Effective Date: September 2026 · Last Updated: September 2026
            </p>
          </header>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">1. Acceptance of Terms</h2>
            <p className="font-body text-sm sm:text-base text-text-secondary leading-relaxed">
              By accessing, browsing, or using TraceSearch (&ldquo;the Service&rdquo;), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any portion of these terms, please discontinue using the service immediately.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">2. Description of the Service</h2>
            <p className="font-body text-sm sm:text-base text-text-secondary leading-relaxed">
              TraceSearch is an AI-assisted research and evidence-tracing platform. The service automates search query planning, gathers public web sources, and provides structured syntheses with interactive citations linking claims back to original publisher URLs.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">3. AI Accuracy and Information Disclaimer</h2>
            <div className="p-4 bg-surface rounded-xl border border-warning/30 space-y-2">
              <div className="flex items-center gap-2 text-warning text-sm font-semibold">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                <span>Informational and Research Purposes Only</span>
              </div>
              <p className="text-xs sm:text-sm text-text-secondary leading-relaxed">
                Outputs produced by TraceSearch are generated via algorithmic search retrieval and artificial intelligence models. While TraceSearch is architected to minimize hallucinations by strictly grounding claims in retrieved sources, automated systems can make mistakes or reflect outdated data.
              </p>
              <p className="text-xs sm:text-sm text-text-secondary leading-relaxed">
                Content generated by TraceSearch does not constitute legal, medical, financial, or certified professional advice. You must independently inspect the linked evidence sources before making critical decisions.
              </p>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">4. Intellectual Property and Third-Party Content</h2>
            <p className="font-body text-sm sm:text-base text-text-secondary leading-relaxed">
              TraceSearch retrieves and displays excerpts from publicly accessible third-party websites. All external content, logos, article titles, and domain names remain the intellectual property of their respective authors and publishers. TraceSearch claims no ownership over third-party content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">5. Acceptable Use Policy</h2>
            <p className="font-body text-sm sm:text-base text-text-secondary leading-relaxed">
              When utilizing TraceSearch, you agree that you will not:
            </p>
            <ul className="list-disc list-inside space-y-1.5 text-xs sm:text-sm text-text-secondary leading-relaxed pl-2">
              <li>Deploy automated scripts, bots, or scrapers to overload or abuse the backend search pipeline.</li>
              <li>Attempt to circumvent API rate limits or security mechanisms.</li>
              <li>Query or disseminate material that violates applicable local or international laws.</li>
              <li>Attempt to reverse engineer the proprietary prompt orchestration and data grounding pipeline.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">6. Limitation of Liability</h2>
            <p className="font-body text-sm sm:text-base text-text-secondary leading-relaxed">
              To the fullest extent permitted by law, TraceSearch and its creator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your access to, use of, or inability to use the service or any information provided therein.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-h3 text-text-primary">7. Contact Information</h2>
            <p className="font-body text-sm sm:text-base text-text-secondary leading-relaxed">
              For any questions, notices, or inquiries concerning these Terms of Service, please reach out to:
            </p>
            <div className="p-4 bg-surface rounded-xl border border-border text-xs sm:text-sm text-text-secondary">
              <span className="font-semibold text-text-primary block mb-0.5">Md Mizan</span>
              <a
                href="mailto:mizanmuhammad20@gmail.com"
                className="text-ocean-deep hover:underline font-mono"
              >
                mizanmuhammad20@gmail.com
              </a>
            </div>
          </section>
        </article>
      </main>

      <Footer />
    </div>
  );
}
